# Generated by Django 4.0.6 on 2024-05-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_login',
            new_name='created_at',
        ),
    ]
