# Generated by Django 4.0.6 on 2024-06-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('person_id', 'person_type')},
        ),
    ]
