# Generated by Django 4.0.6 on 2024-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
    ]
