# Generated by Django 4.0.6 on 2024-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gender',
            field=models.CharField(default='unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
