# Generated by Django 4.0.6 on 2024-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_owner_gender_alter_owner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
