# Generated by Django 4.0.6 on 2024-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_owner_password_alter_tenant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
