# Generated by Django 4.0.6 on 2024-05-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_owner_last_login_tenant_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True)),
                ('social_media_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('tiktok_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.owner')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.tenant')),
            ],
        ),
    ]
