# Generated by Django 4.0.6 on 2024-06-23 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=255)),
                ('year_built', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('district_located', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('apartment_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='apartment_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.owner')),
            ],
            options={
                'db_table': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='TenantIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text="Type of identification document (e.g., Passport, Driver's License)", max_length=255)),
                ('identification_number', models.CharField(help_text='Identification number', max_length=255)),
                ('document_file', models.FileField(help_text='Upload a scan or photo of the identification document.', upload_to='identification_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='accounts_app.tenant')),
            ],
            options={
                'db_table': 'tenant_identifications',
            },
        ),
        migrations.CreateModel(
            name='OwnerIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text="Type of identification document (e.g., Passport, Driver's License)", max_length=255)),
                ('identification_number', models.CharField(help_text='Identification number', max_length=255)),
                ('document_file', models.FileField(help_text='Upload a scan or photo of the identification document.', upload_to='identification_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='accounts_app.owner')),
            ],
            options={
                'db_table': 'owner_identifications',
            },
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_property_app.apartment')),
            ],
            options={
                'db_table': 'apartment_images',
            },
        ),
        migrations.CreateModel(
            name='ApartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_gym', models.BooleanField(default=False)),
                ('has_car_parking', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_alarm', models.BooleanField(default=False)),
                ('has_air_conditioner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rental_property_app.apartment')),
            ],
            options={
                'db_table': 'apartment_features',
            },
        ),
    ]
