# Generated by Django 4.0.6 on 2024-06-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominvoice',
            name='invoice_number',
            field=models.CharField(default='', editable=False, max_length=12, unique=True),
        ),
    ]
