# Generated by Django 4.0.6 on 2024-06-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('rental_property_app', '0002_roominvoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('year_built', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('district_located', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('house_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=255)),
                ('no_of_bathrooms', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='accounts_app.owner')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
        migrations.CreateModel(
            name='HouseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='', editable=False, max_length=12, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rental_property_app.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_invoices', to='accounts_app.tenant')),
            ],
            options={
                'db_table': 'house_invoices',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_property_app.house')),
            ],
            options={
                'db_table': 'house_images',
            },
        ),
        migrations.CreateModel(
            name='HouseComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=255)),
                ('complaint_description', models.TextField()),
                ('complaint_status', models.CharField(choices=[('Unresolved', 'Unresolved'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Unresolved', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='rental_property_app.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_complaints', to='accounts_app.tenant')),
            ],
            options={
                'db_table': 'house_complaints',
            },
        ),
        migrations.CreateModel(
            name='HouseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rental_property_app.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_assignments', to='accounts_app.tenant')),
            ],
            options={
                'db_table': 'house_assignments',
            },
        ),
    ]
