# Generated by Django 4.0.6 on 2024-06-30 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('passport_no', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='buyer_signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('has_representor', models.BooleanField(default=False)),
                ('image_path', models.ImageField(upload_to='buyer_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buyers',
            },
        ),
        migrations.CreateModel(
            name='BuyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_located', models.CharField(max_length=255)),
                ('property_size', models.CharField(max_length=255)),
                ('lotto_no', models.CharField(max_length=255)),
                ('local_government', models.CharField(max_length=255)),
                ('court_district', models.CharField(max_length=255)),
                ('on_east', models.CharField(max_length=255)),
                ('on_south', models.CharField(max_length=255)),
                ('on_west', models.CharField(max_length=255)),
                ('on_north', models.CharField(max_length=255)),
                ('judge_person', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='buying_property_app.buyer')),
            ],
            options={
                'db_table': 'buy_properties',
            },
        ),
        migrations.CreateModel(
            name='OwnerBuyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('identity', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('owner', 'Owner'), ('representor', 'Representor')], max_length=255)),
                ('image_path', models.ImageField(upload_to='owner_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_properties', to='accounts_app.owner')),
            ],
            options={
                'db_table': 'owner_buy_properties',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('buy_property', 'Buy Property')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='witness_signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('identity_guarantor', 'Identity Guarantor'), ('financial_guarantor', 'Financial Guarantor')], max_length=255)),
                ('image_path', models.ImageField(upload_to='witness_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'witnesses',
            },
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='buying_property_app.buyproperty')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='buying_property_app.buyer')),
            ],
            options={
                'db_table': 'property_prices',
            },
        ),
        migrations.CreateModel(
            name='PropertyDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed_number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='buying_property_app.buyproperty')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='buying_property_app.buyer')),
                ('owner_buy_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='buying_property_app.ownerbuyproperty')),
                ('property_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='buying_property_app.propertyprice')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='buying_property_app.witness')),
            ],
            options={
                'db_table': 'property_deeds',
            },
        ),
        migrations.CreateModel(
            name='PropertyBuyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='property_buy_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buying_property_app.buyproperty')),
            ],
            options={
                'db_table': 'property_buy_images',
            },
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='owner_buy_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='buying_property_app.ownerbuyproperty'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='buying_property_app.witness'),
        ),
    ]
